<?php

/**
 * BaseaBlogCategoryGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $blog_category_id
 * @property integer $group_id
 * @property aBlogCategory $BlogCategory
 * @property sfGuardGroup $Group
 * 
 * @method integer            getBlogCategoryId()   Returns the current record's "blog_category_id" value
 * @method integer            getGroupId()          Returns the current record's "group_id" value
 * @method aBlogCategory      getBlogCategory()     Returns the current record's "BlogCategory" value
 * @method sfGuardGroup       getGroup()            Returns the current record's "Group" value
 * @method aBlogCategoryGroup setBlogCategoryId()   Sets the current record's "blog_category_id" value
 * @method aBlogCategoryGroup setGroupId()          Sets the current record's "group_id" value
 * @method aBlogCategoryGroup setBlogCategory()     Sets the current record's "BlogCategory" value
 * @method aBlogCategoryGroup setGroup()            Sets the current record's "Group" value
 * 
 * @package    asandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseaBlogCategoryGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('a_blog_category_group');
        $this->hasColumn('blog_category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('group_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));

        $this->option('type', 'INNODB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('aBlogCategory as BlogCategory', array(
             'local' => 'blog_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}